steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: wlgore-s
    integrationFlowId: P2005880373-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: wlgore-s
    integrationFlowId: P2005880373-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: wlgore-s
    integrationFlowId: P2005880373-flow4
    integrationFlowName: P2005880373-flow4
    packageId: CICD
    filePath: P2005880373-flow4.zip